name: matlab

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
    - "**.m"
    - "**.c"
    - ".github/workflows/ci.yml"

jobs:

  core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        matlab: [R2022b]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.matlab }}

    - uses: actions/checkout@v4

    - name: Run Matlab tests (buildtool)
      timeout-minutes: 10
      uses: matlab-actions/run-build@v1
